from tkinter import *
# from Util.Gui_main import MainWindow
import tkinter


class SuFuncWindow():
    def __init__(self, mainwindow):
        self.mainwindow = mainwindow
        self.su_FuncWindow()
        
    def su_FuncWindow(self):
        self.frame_su_start_daily = tkinter.StringVar()
        self.frame_su_stop_daily = tkinter.StringVar()
        self.frame_su_worksign = tkinter.StringVar()
        self.frame_su_standsign = tkinter.StringVar()
        self.frame_su_common = Frame(self.mainwindow)
        self.frame_su_common.grid(row=0,column=0,pady=15,sticky=N)
        self.frame_su_common_title = Label(self.frame_su_common,text="【通用指令】",font=("Arial",18))
        self.frame_su_common_title.grid(row=0,column=0,padx=10,sticky=W)
        self.frame_su_common_ADAS_query = Button(self.frame_su_common,text="ADAS查询指令",command="",bd=5,width=15)
        self.frame_su_common_ADAS_query.grid(row=1,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_common_DSM_query = Button(self.frame_su_common,text="DSM查询指令",command="",bd=5,width=14)
        self.frame_su_common_DSM_query.grid(row=1,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_common_ADAS_default = Button(self.frame_su_common,text="恢复ADAS默认参数",command="",bd=5)
        self.frame_su_common_ADAS_default.grid(row=2,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_common_DSM_default = Button(self.frame_su_common,text="恢复DSM默认参数",command="",bd=5)
        self.frame_su_common_DSM_default.grid(row=2,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_common_ADAS_infor = Button(self.frame_su_common,text="读取ADAS基本信息",command="",bd=5)
        self.frame_su_common_ADAS_infor.grid(row=3,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_common_DSM_infor = Button(self.frame_su_common,text="读取DSM基本信息",command="",bd=5)
        self.frame_su_common_DSM_infor.grid(row=3,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_para = Frame(self.mainwindow)
        self.frame_su_para.grid(row=0,column=1,pady=15,sticky=N)
        self.frame_su_para_title = Label(self.frame_su_para,text="【参数操作】",font=("Arial",18))
        self.frame_su_para_title.grid(row=0,column=0,padx=10,sticky=W)
        self.frame_su_para_case = Label(self.frame_su_para,text="用例：")
        self.frame_su_para_case.grid(row=1,column=0,ipadx=20,ipady=5,pady=11,sticky=W)
        self.frame_su_para_select = Button(self.frame_su_para,text="选择用例",command="",bd=5,width=15)
        self.frame_su_para_select.grid(row=2,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_para_exe = Button(self.frame_su_para,text="执行用例",command="",bd=5,width=15)
        self.frame_su_para_exe.grid(row=2,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_para_ADAS = Button(self.frame_su_para,text="查询ADAS参数",command="",bd=5,width=15)
        self.frame_su_para_ADAS.grid(row=3,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_para_DSM = Button(self.frame_su_para,text="查询DSM参数",command="",bd=5,width=15)
        self.frame_su_para_DSM.grid(row=3,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_state = Frame(self.mainwindow)
        self.frame_su_state.grid(row=1,column=0,pady=15,sticky=N)
        self.frame_su_state_title = Label(self.frame_su_state,text="【外设状态】",font=("Arial",18))
        self.frame_su_state_title.grid(row=0,column=0,padx=10,sticky=W)
        self.frame_su_state_ADAS = Button(self.frame_su_state,text="查询ADAS工作状态",command="",bd=5)
        self.frame_su_state_ADAS.grid(row=1,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_state_DSM = Button(self.frame_su_state,text="查询DSM工作状态",command="",bd=5)
        self.frame_su_state_DSM.grid(row=1,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_picture = Frame(self.mainwindow)
        self.frame_su_picture.grid(row=1,column=1,pady=15,sticky=N)
        self.frame_su_picture_title = Label(self.frame_su_picture,text="【抓        拍】",font=("Arial",18))
        self.frame_su_picture_title.grid(row=0,column=0,padx=5,sticky=W)
        self.frame_su_picture_ADAS = Button(self.frame_su_picture,text="ADAS主动抓拍",command="",bd=5,width=15)
        self.frame_su_picture_ADAS.grid(row=1,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_picture_DSM = Button(self.frame_su_picture,text="DSM主动抓拍",command="",bd=5,width=15)
        self.frame_su_picture_DSM.grid(row=1,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_daily = Frame(self.mainwindow)
        self.frame_su_daily.grid(row=2,column=0,pady=15,sticky=N)
        self.frame_su_daily_title = Label(self.frame_su_daily,text="【日志操作】",font=("Arial",18))
        self.frame_su_daily_title.grid(row=0,column=0,padx=10,sticky=W)
        self.frame_su_daily_start = Label(self.frame_su_daily,text="输入起始日期：",bd=5,width=10)
        self.frame_su_daily_start.grid(row=1,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_daily_startcont = Entry(self.frame_su_daily,textvariable=self.frame_su_start_daily,bd=5,width=16)
        self.frame_su_daily_startcont.grid(row=1,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_daily_stop = Label(self.frame_su_daily,text="输入结束日期：",bd=5,width=10)
        self.frame_su_daily_stop.grid(row=2,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_daily_stopcont = Entry(self.frame_su_daily,textvariable=self.frame_su_stop_daily,bd=5,width=16)
        self.frame_su_daily_stopcont.grid(row=2,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_daily_exe = Button(self.frame_su_daily,text="获取日志",command="",bd=5)
        self.frame_su_daily_exe.grid(row=3,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_mode = Frame(self.mainwindow)
        self.frame_su_mode.grid(row=2,column=1,pady=15,sticky=N)
        self.frame_su_mode_title = Label(self.frame_su_mode,text="【模式操作】",font=("Arail",18))
        self.frame_su_mode_title.grid(row=0,column=0,padx=20,sticky=W)
        self.frame_su_mode_work = Label(self.frame_su_mode,text="输入工作模式：",bd=5,width=13)
        self.frame_su_mode_work.grid(row=1,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_mode_worksign = Entry(self.frame_su_mode,textvariable=self.frame_su_worksign,bd=5,width=15)
        self.frame_su_mode_worksign.grid(row=1,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_mode_stand = Label(self.frame_su_mode,text="输入标准模式：",bd=5,width=13)
        self.frame_su_mode_stand.grid(row=2,column=0,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_mode_standsign = Entry(self.frame_su_mode,textvariable=self.frame_su_standsign,bd=5,width=15)
        self.frame_su_mode_standsign.grid(row=2,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        self.frame_su_mode_exe = Button(self.frame_su_mode,text="模式切换",command="",bd=5)
        self.frame_su_mode_exe.grid(row=3,column=1,ipadx=20,ipady=5,pady=5,sticky=W)
        